# Generated by Django 3.1.7 on 2021-09-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
